### ISSUE TITLE
master branch running error

### ISSUE THREAD

**Issue by xz-blender** [atticus-lv/BlenderExtensionManager#3]
```
(venv) PS E:\BEM> python main.py --dev
Traceback (most recent call last):
  File "E:\BEM\main.py", line 4, in <module>
    from views import main_window
  File "E:\BEM\views\main_window.py", line 3, in <module>
    from views.setttings_view import config
ImportError: cannot import name 'config' from 'views.setttings_view' (E:\BEM\views\setttings_view.py)
```

**Comment by atticus-lv** [comment]
已经修复
