### ISSUE TITLE
无法运行python main.py --web

### ISSUE THREAD

**Issue by chenpaner** [atticus-lv/BlenderExtensionManager#4]
你好，请问下分支运行报错,

```
(venv) D:\Blender\插件修改\edit addon\BlenderExtensionManager>python main.py --web
Traceback (most recent call last):
  File "D:\Blender\插件修改\edit addon\BlenderExtensionManager\main.py", line 28, in <module>
    main_window.draw()
  File "D:\Blender\插件修改\edit addon\BlenderExtensionManager\views\main_window.py", line 40, in draw
    blender_view.draw()
  File "D:\Blender\插件修改\edit addon\BlenderExtensionManager\views\blender_view.py", line 26, in draw
    load_all(container)
  File "D:\Blender\插件修改\edit addon\BlenderExtensionManager\view_model\blender_card.py", line 154, in load_all
    blenders = Blender.load_all_from_db()
  File "D:\Blender\插件修改\edit addon\BlenderExtensionManager\model\blender.py", line 138, in load_all_from_db
    with open_db(Blender.db_path()) as (conn, c):
  File "C:\Users\CP\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "D:\Blender\插件修改\edit addon\BlenderExtensionManager\model\blender.py", line 11, in open_db
    conn = sqlite3.connect(str(db_path))
sqlite3.OperationalError: unable to open database file
```
 我查看blender.py代码里有个blender.db文件，请问这个是怎么生成啊，我看blender安装文件里只有个blender.pdb啊
python main.py --dev运行也是一样的报错

**Comment by atticus-lv** [comment]
这是保存blender数据的数据库文件...添加了blender应该就能生成...可能是缺失了文件夹的问题...我之后把他挪动到用户文件夹试试
